import { GoogleGenerativeAI } from "@google/generative-ai";

/**
 * Gets the configured Gemini model name from environment variables,
 * falling back to "gemini-3.6-flash".
 */
export function getGeminiModelName(): string {
  return process.env.GEMINI_MODEL || "gemini-3.6-flash";
}

/**
 * Calls the Gemini API using the configured model.
 *
 * @param prompt - The prompt text to send to Gemini.
 * @returns The text response generated by Gemini.
 * @throws Error if GEMINI_API_KEY is missing or if the API call fails.
 */
export async function callGemini(prompt: string): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY;

  if (!apiKey) {
    throw new Error(
      "GEMINI_API_KEY environment variable is missing. Please set GEMINI_API_KEY in your environment or .env.local file."
    );
  }

  const modelName = getGeminiModelName();

  try {
    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ model: modelName });

    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text();

    return text;
  } catch (error: any) {
    throw new Error(
      `Gemini API call failed (model: ${modelName}): ${error?.message || String(error)}`
    );
  }
}
